AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "TODO"
Description: "Create EC2 for script execution"
Parameters:
  KeyNameParameter:
    Type: String
    Description: Enter key name
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.medium
    Description: Enter t2.micro, t2.medium. Default is t2.micro.
  ImageIdParameter:
    Type: String
    Default: ami-042e8287309f5df03 
    AllowedValues:
      - ami-042e8287309f5df03 
    Description: ami-042e8287309f5df03 is x86 Ubuntu 20.04 in us-east-1
Resources:
    EC2Instance:
        Type: "AWS::EC2::Instance"
        Properties:
            ImageId: !Ref ImageIdParameter
            InstanceType: !Ref InstanceTypeParameter
            KeyName: !Ref KeyNameParameter 
            AvailabilityZone: "us-east-1b"
            SubnetId: "subnet-1792365f"
            BlockDeviceMappings:
              - DeviceName: /dev/sda1
                Ebs:
                  VolumeSize: 50
            EbsOptimized: false
            SecurityGroupIds: 
              - "sg-14ae545d"
            SourceDestCheck: true
            UserData:
              Fn::Base64: !Sub |
                 #!/bin/bash -ex
                 apt-get update -y
                 apt-get upgrade -y
                 apt-get install git -y
                 git clone https://github.com/aws-deepracer-community/deepracer-for-cloud.git
                 cd /deepracer-for-cloud && ./bin/prepare.sh
                 echo hello >> /tmp/hello.txt
            Tags: 
              - 
                Key: "Name"
                Value: "deepracer sandbox"
              - 
                Key: "Project"
                Value: "deepracer sandbox"   